

---

- hosts: all
  become: true
  tasks:


  - name: install apache and php
    apt:   #ubuntu OS package manager
      name: 
        - apache2
        - libapache2-mod-php
      state: latest  
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: install apache and php
    dnf:   #CentOS OS package manager
      name: 
        - httpd
        - php
      state: latest  
      update_cache: yes
    when: ansible_distribution == "CentOS"
  






