

---

- hosts: all
  become: true
  tasks:


  - name: install apache and php
    package: #generic OS package manager, yum,apt or dnf, etc 
      name: 
        - "{{apache_package}}"
        - "{{php_package}}"
      state: latest  
      update_cache: yes
  






