

---
- hosts: all
  become: true
  tasks:

  - name: update repo cacche (CentOS)
    tags: always
    dnf:
      update_cache: yes                       # make sure repository indices are not stale, else our play could fail
    changed_when: false                       # Have control of what is considered a change. we will not see change = 1 anytime the cache is updated, to keep the logs clean 
    when: ansible_distribution == "CentOS" 


  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu" 


  - name: add ssh key for simone
    tags: always
    authorized_key: 
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH3Db/5f2cXO4n3+NqALwYM05ITMUxMtkflrz9L1QnwP ansible"  # ansible key for this env
  

- hosts: workstations
  become: true
  tasks: 

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive: 
     src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
     dest: /usr/local/bin
     remote_src: yes 
     mode: 0755
     owner: root
     group: root
          


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php
    tags: apache,apache2,ubuntu
    apt:   #ubuntu OS package manager
      name: 
        - apache2
        - libapache2-mod-php
      state: latest  
    when: ansible_distribution == "Ubuntu"


  - name: install apache and php
    tags: apache,centos,httpd
    dnf:   #CentOS OS package manager
      name: 
        - httpd
        - php
      state: latest  
    when: ansible_distribution == "CentOS"
 
  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"


  - name: change email address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf        # path to file that would be changed
      regexp: '^ServerAdmin'                  # line must begin as shown, no space before ServerAdmin
      line: ServerAdmin fnchocho@gmail.com    # new change, Your address, where problems with the server should be sent 
    when: ansible_distribution == "CentOS"    # Only for centos os, since would be diff for ubuntu
    register: httpd                           # allow us capture the state of a new variable called httpd, could be named anything!


  - name: restart httpd (CentOS)
    tags: CentOS,apache,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed          #after play change email play runs, would generate variable httpd and would trigger httpd restart play ONLY if there was a change  
    



  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644



- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: 
        - mariadb
      state: latest  
    when: ansible_distribution == "CentOS"


  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: 
        - mariadb-server
      state: latest  
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:  # name of package is same for both OS
      name: samba  
      state: latest  
  




