
- name: add ssh key for simone
  tags: always
  authorized_key: 
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH3Db/5f2cXO4n3+NqALwYM05ITMUxMtkflrz9L1QnwP ansible"  # ansible key for this env

- name: generate sshd_config file from template
  tags: ssh
  template: 
      src: "{{ ssh_template_file }}"
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0644
  notify: restart_sshd 



